### ISSUE TITLE
Prioritize beatmaps that weren't recommended recently

### ISSUE THREAD

**Issue by praeludiumOrbis** [ojcastaneda/osu-stamina-trainer#2]
To 1) get variety in the recommended beatmaps and 2) to prevent the same beatmap from being recommended several times with filters that aren't too specific

Context: https://discord.com/channels/860588898857254933/860589529618579467/883159171376218162

**Comment by ojcastaneda** [comment]
As part of the recent update for the bot/[server](https://github.com/ojcastaneda/osu-stamina-trainer-server). I implemented a mechanism that targets the less recently requested map. This way, it should not happen as often. But if the requests are done in a short amount of time, it might show the same behavior. Since differences in response times between the different components might affect the order in which they are returned. I will leave this issue open for a week if there is any bug related to this implementation.
